import json
import re

with open('political-entity.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Example mapping for vivid, intuitive, and geo-appended names
geo_map = {
    'Egypt': '埃及',
    'Sumer': '苏美尔',
    'Babylon': '巴比伦',
    'Assyria': '亚述',
    'Phoenicia': '腓尼基',
    'Greece': '希腊',
    'Rome': '罗马',
    'Persia': '波斯',
    'India': '印度',
    'China': '中国',
    'Japan': '日本',
    'Korea': '朝鲜半岛',
    'Maya': '玛雅',
    'Inca': '印加',
    'Aztec': '阿兹特克',
    'Olmec': '奥尔梅克',
    'Zapotec': '萨波特克',
    'Mixtec': '米斯特克',
    'Toltec': '托尔特克',
    'Cherokee': '切罗基',
    'Sioux': '苏族',
    'Navajo': '纳瓦霍',
    'Apache': '阿帕奇',
    'Comanche': '科曼奇',
    'Iroquois': '易洛魁',
    'Hopewell': '霍普韦尔',
    'Adena': '阿德纳',
    'Mississippian': '密西西比',
    'Moche': '莫切',
    'Nazca': '纳斯卡',
    'Chimu': '奇穆',
    'Wari': '瓦里',
    'Tiahuanaco': '蒂亚瓦纳科',
    'Chachapoya': '查查波亚',
    'Paracas': '帕拉卡斯',
    'Teotihuacan': '特奥蒂瓦坎',
    'Tarascan': '塔拉斯坎',
    'Ryukyu': '琉球',
    'Jomon': '绳文',
    'Yayoi': '弥生',
    'Kofun': '古坟',
    'Heian': '平安',
    'Nara': '奈良',
    'Asuka': '飞鸟',
    'Muromachi': '室町',
    'Kamakura': '镰仓',
    'Azuchi-Momoyama': '安土桃山',
    'Edo': '江户',
    'Yamato': '大和',
    'Wa': '倭',
    'Emishi': '虾夷',
    'Ainu': '阿伊努',
    'Poland': '波兰',
    'France': '法兰西',
    'Germany': '德意志',
    'England': '英格兰',
    'Scotland': '苏格兰',
    'Ireland': '爱尔兰',
    'Spain': '西班牙',
    'Portugal': '葡萄牙',
    'Russia': '俄罗斯',
    'Ukraine': '乌克兰',
    'Hungary': '匈牙利',
    'Czech': '捷克',
    'Slovak': '斯洛伐克',
    'Austria': '奥地利',
    'Sweden': '瑞典',
    'Norway': '挪威',
    'Denmark': '丹麦',
    'Finland': '芬兰',
    'Switzerland': '瑞士',
    'Netherlands': '荷兰',
    'Belgium': '比利时',
    'Turkey': '土耳其',
    'Arab': '阿拉伯',
    'Mongol': '蒙古',
    'Tibet': '西藏',
    'Vietnam': '越南',
    'Thailand': '泰国',
    'Laos': '老挝',
    'Cambodia': '柬埔寨',
    'Myanmar': '缅甸',
    'Malaysia': '马来西亚',
    'Indonesia': '印度尼西亚',
    'Philippines': '菲律宾',
    'Australia': '澳大利亚',
    'New Zealand': '新西兰',
    'Papua': '巴布亚',
    'Fiji': '斐济',
    'Samoa': '萨摩亚',
    'Tonga': '汤加',
    'Hawaii': '夏威夷',
    'Greenland': '格陵兰',
    'Canada': '加拿大',
    'America': '美洲',
    'United States': '美国',
    'Mexico': '墨西哥',
    'Brazil': '巴西',
    'Argentina': '阿根廷',
    'Chile': '智利',
    'Peru': '秘鲁',
    'Colombia': '哥伦比亚',
    'Venezuela': '委内瑞拉',
    'Bolivia': '玻利维亚',
    'Paraguay': '巴拉圭',
    'Uruguay': '乌拉圭',
    'Ecuador': '厄瓜多尔',
    'Guyana': '圭亚那',
    'Suriname': '苏里南',
    'French Guiana': '法属圭亚那',
    'Africa': '非洲',
    'Morocco': '摩洛哥',
    'Algeria': '阿尔及利亚',
    'Tunisia': '突尼斯',
    'Libya': '利比亚',
    'Egypt': '埃及',
    'Sudan': '苏丹',
    'Ethiopia': '埃塞俄比亚',
    'Somalia': '索马里',
    'Kenya': '肯尼亚',
    'Uganda': '乌干达',
    'Tanzania': '坦桑尼亚',
    'Rwanda': '卢旺达',
    'Burundi': '布隆迪',
    'Congo': '刚果',
    'Gabon': '加蓬',
    'Angola': '安哥拉',
    'Namibia': '纳米比亚',
    'Botswana': '博茨瓦纳',
    'Zimbabwe': '津巴布韦',
    'Mozambique': '莫桑比克',
    'South Africa': '南非',
    'Lesotho': '莱索托',
    'Swaziland': '斯威士兰',
    'Madagascar': '马达加斯加',
    'Mauritius': '毛里求斯',
    'Seychelles': '塞舌尔',
    'Comoros': '科摩罗',
    'Djibouti': '吉布提',
    'Eritrea': '厄立特里亚',
    'Chad': '乍得',
    'Niger': '尼日尔',
    'Mali': '马里',
    'Burkina Faso': '布基纳法索',
    'Senegal': '塞内加尔',
    'Gambia': '冈比亚',
    'Guinea': '几内亚',
    'Sierra Leone': '塞拉利昂',
    'Liberia': '利比里亚',
    'Ivory Coast': '科特迪瓦',
    'Ghana': '加纳',
    'Togo': '多哥',
    'Benin': '贝宁',
    'Nigeria': '尼日利亚',
    'Cameroon': '喀麦隆',
    'Central African': '中非',
    'Equatorial Guinea': '赤道几内亚',
    'Sao Tome': '圣多美',
    'Cape Verde': '佛得角',
    'Guinea-Bissau': '几内亚比绍',
    'Zambia': '赞比亚',
    'Malawi': '马拉维',
    'Tanzania': '坦桑尼亚',
    'Somaliland': '索马里兰',
    'Morocco': '摩洛哥',
    'Western Sahara': '西撒哈拉',
    'Sudan': '苏丹',
    'South Sudan': '南苏丹',
    'Libya': '利比亚',
    'Tunisia': '突尼斯',
    'Algeria': '阿尔及利亚',
    'Mauritania': '毛里塔尼亚',
    'Niger': '尼日尔',
    'Chad': '乍得',
    'Mali': '马里',
    'Burkina Faso': '布基纳法索',
    'Senegal': '塞内加尔',
    'Gambia': '冈比亚',
    'Guinea': '几内亚',
    'Sierra Leone': '塞拉利昂',
    'Liberia': '利比里亚',
    'Ivory Coast': '科特迪瓦',
    'Ghana': '加纳',
    'Togo': '多哥',
    'Benin': '贝宁',
    'Nigeria': '尼日利亚',
    'Cameroon': '喀麦隆',
    'Central African': '中非',
    'Equatorial Guinea': '赤道几内亚',
    'Sao Tome': '圣多美',
    'Cape Verde': '佛得角',
    'Guinea-Bissau': '几内亚比绍',
    'Zambia': '赞比亚',
    'Malawi': '马拉维',
    'Tanzania': '坦桑尼亚',
    'Somaliland': '索马里兰',
    'Morocco': '摩洛哥',
    'Western Sahara': '西撒哈拉',
    'Sudan': '苏丹',
    'South Sudan': '南苏丹',
    'Libya': '利比亚',
    'Tunisia': '突尼斯',
    'Algeria': '阿尔及利亚',
    'Mauritania': '毛里塔尼亚',
    'Niger': '尼日尔',
    'Chad': '乍得',
    'Mali': '马里',
    'Burkina Faso': '布基纳法索',
    'Senegal': '塞内加尔',
    'Gambia': '冈比亚',
    'Guinea': '几内亚',
    'Sierra Leone': '塞拉利昂',
    'Liberia': '利比里亚',
    'Ivory Coast': '科特迪瓦',
    'Ghana': '加纳',
    'Togo': '多哥',
    'Benin': '贝宁',
    'Nigeria': '尼日利亚',
    'Cameroon': '喀麦隆',
    'Central African': '中非',
    'Equatorial Guinea': '赤道几内亚',
    'Sao Tome': '圣多美',
    'Cape Verde': '佛得角',
    'Guinea-Bissau': '几内亚比绍',
    'Zambia': '赞比亚',
    'Malawi': '马拉维',
    'Tanzania': '坦桑尼亚',
    'Somaliland': '索马里兰',
}

def polish_chinese_name(eng, chi):
    # Try to append geo info if not already present
    for k, v in geo_map.items():
        if k.lower() in eng.lower() and v not in chi:
            return chi + f"（{v}）"
    return chi

for entry in data:
    entry[1] = polish_chinese_name(entry[0], entry[1])

with open('political-entity.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
